language: cpp
compiler:
  - clang
sudo: false
cache: ccache
os: linux
matrix:
  include:
    - name: "Linter"
      node_js: "latest"
      env:
        - NODE=$(which node)
      script:
        - make lint
        # Lint the first commit in the PR.
        - git log $TRAVIS_COMMIT_RANGE --pretty=format:'%h' --no-merges | tail -1 | xargs npx core-validate-commit --no-validate-metadata
    - name: "Test Suite"
      install:
        - ./configure
        - make -j2 V=
      script:
        - make -j2 test
      before_install:
        - export CXX="ccache clang++ -Qunused-arguments"
        - export CC="ccache clang -Qunused-arguments -Wno-unknown-warning-option"
        - export JOBS=2
